// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.3
// source: chatwebhook.proto

package chatwebhook_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatWebHook_Subscribe_FullMethodName = "/chatwebhook.ChatWebHook/Subscribe"
)

// ChatWebHookClient is the client API for ChatWebHook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatWebHookClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type chatWebHookClient struct {
	cc grpc.ClientConnInterface
}

func NewChatWebHookClient(cc grpc.ClientConnInterface) ChatWebHookClient {
	return &chatWebHookClient{cc}
}

func (c *chatWebHookClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatWebHook_ServiceDesc.Streams[0], ChatWebHook_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatWebHook_SubscribeClient = grpc.ServerStreamingClient[Event]

// ChatWebHookServer is the server API for ChatWebHook service.
// All implementations must embed UnimplementedChatWebHookServer
// for forward compatibility.
type ChatWebHookServer interface {
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedChatWebHookServer()
}

// UnimplementedChatWebHookServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatWebHookServer struct{}

func (UnimplementedChatWebHookServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedChatWebHookServer) mustEmbedUnimplementedChatWebHookServer() {}
func (UnimplementedChatWebHookServer) testEmbeddedByValue()                     {}

// UnsafeChatWebHookServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatWebHookServer will
// result in compilation errors.
type UnsafeChatWebHookServer interface {
	mustEmbedUnimplementedChatWebHookServer()
}

func RegisterChatWebHookServer(s grpc.ServiceRegistrar, srv ChatWebHookServer) {
	// If the following call panics, it indicates UnimplementedChatWebHookServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatWebHook_ServiceDesc, srv)
}

func _ChatWebHook_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatWebHookServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatWebHook_SubscribeServer = grpc.ServerStreamingServer[Event]

// ChatWebHook_ServiceDesc is the grpc.ServiceDesc for ChatWebHook service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatWebHook_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatwebhook.ChatWebHook",
	HandlerType: (*ChatWebHookServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _ChatWebHook_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chatwebhook.proto",
}
