// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: chatwebhook.proto

package chatwebhook_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlatformID int32

const (
	PlatformID_platformIDUndefined PlatformID = 0
	PlatformID_platformIDKick      PlatformID = 1
	PlatformID_platformIDTwitch    PlatformID = 2
	PlatformID_platformIDYouTube   PlatformID = 3
)

// Enum value maps for PlatformID.
var (
	PlatformID_name = map[int32]string{
		0: "platformIDUndefined",
		1: "platformIDKick",
		2: "platformIDTwitch",
		3: "platformIDYouTube",
	}
	PlatformID_value = map[string]int32{
		"platformIDUndefined": 0,
		"platformIDKick":      1,
		"platformIDTwitch":    2,
		"platformIDYouTube":   3,
	}
)

func (x PlatformID) Enum() *PlatformID {
	p := new(PlatformID)
	*p = x
	return p
}

func (x PlatformID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlatformID) Descriptor() protoreflect.EnumDescriptor {
	return file_chatwebhook_proto_enumTypes[0].Descriptor()
}

func (PlatformID) Type() protoreflect.EnumType {
	return &file_chatwebhook_proto_enumTypes[0]
}

func (x PlatformID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlatformID.Descriptor instead.
func (PlatformID) EnumDescriptor() ([]byte, []int) {
	return file_chatwebhook_proto_rawDescGZIP(), []int{0}
}

type PlatformEventType int32

const (
	PlatformEventType_platformEventTypeUndefined              PlatformEventType = 0
	PlatformEventType_platformEventTypeChatMessage            PlatformEventType = 1
	PlatformEventType_platformEventTypeCheer                  PlatformEventType = 2
	PlatformEventType_platformEventTypeAdBreak                PlatformEventType = 4
	PlatformEventType_platformEventTypeFollow                 PlatformEventType = 6
	PlatformEventType_platformEventTypeStreamOnline           PlatformEventType = 256
	PlatformEventType_platformEventTypeStreamOffline          PlatformEventType = 257
	PlatformEventType_platformEventTypeStreamInfoUpdate       PlatformEventType = 258
	PlatformEventType_platformEventTypeSubscriptionNew        PlatformEventType = 512
	PlatformEventType_platformEventTypeSubscriptionRenewed    PlatformEventType = 513
	PlatformEventType_platformEventTypeGiftedSubscription     PlatformEventType = 514
	PlatformEventType_platformEventTypeRaid                   PlatformEventType = 768
	PlatformEventType_platformEventTypeChannelShoutoutReceive PlatformEventType = 769
	PlatformEventType_platformEventTypeBan                    PlatformEventType = 1024
	PlatformEventType_platformEventTypeAutoModHold            PlatformEventType = 1025
	PlatformEventType_platformEventTypeChannelPointRedemption PlatformEventType = 1280
	PlatformEventType_platformEventTypeOther                  PlatformEventType = 65535
)

// Enum value maps for PlatformEventType.
var (
	PlatformEventType_name = map[int32]string{
		0:     "platformEventTypeUndefined",
		1:     "platformEventTypeChatMessage",
		2:     "platformEventTypeCheer",
		4:     "platformEventTypeAdBreak",
		6:     "platformEventTypeFollow",
		256:   "platformEventTypeStreamOnline",
		257:   "platformEventTypeStreamOffline",
		258:   "platformEventTypeStreamInfoUpdate",
		512:   "platformEventTypeSubscriptionNew",
		513:   "platformEventTypeSubscriptionRenewed",
		514:   "platformEventTypeGiftedSubscription",
		768:   "platformEventTypeRaid",
		769:   "platformEventTypeChannelShoutoutReceive",
		1024:  "platformEventTypeBan",
		1025:  "platformEventTypeAutoModHold",
		1280:  "platformEventTypeChannelPointRedemption",
		65535: "platformEventTypeOther",
	}
	PlatformEventType_value = map[string]int32{
		"platformEventTypeUndefined":              0,
		"platformEventTypeChatMessage":            1,
		"platformEventTypeCheer":                  2,
		"platformEventTypeAdBreak":                4,
		"platformEventTypeFollow":                 6,
		"platformEventTypeStreamOnline":           256,
		"platformEventTypeStreamOffline":          257,
		"platformEventTypeStreamInfoUpdate":       258,
		"platformEventTypeSubscriptionNew":        512,
		"platformEventTypeSubscriptionRenewed":    513,
		"platformEventTypeGiftedSubscription":     514,
		"platformEventTypeRaid":                   768,
		"platformEventTypeChannelShoutoutReceive": 769,
		"platformEventTypeBan":                    1024,
		"platformEventTypeAutoModHold":            1025,
		"platformEventTypeChannelPointRedemption": 1280,
		"platformEventTypeOther":                  65535,
	}
)

func (x PlatformEventType) Enum() *PlatformEventType {
	p := new(PlatformEventType)
	*p = x
	return p
}

func (x PlatformEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlatformEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_chatwebhook_proto_enumTypes[1].Descriptor()
}

func (PlatformEventType) Type() protoreflect.EnumType {
	return &file_chatwebhook_proto_enumTypes[1]
}

func (x PlatformEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlatformEventType.Descriptor instead.
func (PlatformEventType) EnumDescriptor() ([]byte, []int) {
	return file_chatwebhook_proto_rawDescGZIP(), []int{1}
}

type Currency int32

const (
	Currency_CURRENCY_UNDEFINED   Currency = 0
	Currency_CURRENCY_USD         Currency = 1
	Currency_CURRENCY_EUR         Currency = 2
	Currency_CURRENCY_GBP         Currency = 3
	Currency_CURRENCY_JPY         Currency = 4
	Currency_CURRENCY_TWITCH_BITS Currency = 1024
	Currency_CURRENCY_OTHER       Currency = 65535
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0:     "CURRENCY_UNDEFINED",
		1:     "CURRENCY_USD",
		2:     "CURRENCY_EUR",
		3:     "CURRENCY_GBP",
		4:     "CURRENCY_JPY",
		1024:  "CURRENCY_TWITCH_BITS",
		65535: "CURRENCY_OTHER",
	}
	Currency_value = map[string]int32{
		"CURRENCY_UNDEFINED":   0,
		"CURRENCY_USD":         1,
		"CURRENCY_EUR":         2,
		"CURRENCY_GBP":         3,
		"CURRENCY_JPY":         4,
		"CURRENCY_TWITCH_BITS": 1024,
		"CURRENCY_OTHER":       65535,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_chatwebhook_proto_enumTypes[2].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_chatwebhook_proto_enumTypes[2]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_chatwebhook_proto_rawDescGZIP(), []int{2}
}

type TextFormatType int32

const (
	TextFormatType_TEXT_FORMAT_TYPE_UNDEFINED TextFormatType = 0
	TextFormatType_TEXT_FORMAT_TYPE_PLAIN     TextFormatType = 1
	TextFormatType_TEXT_FORMAT_TYPE_MARKDOWN  TextFormatType = 2
	TextFormatType_TEXT_FORMAT_TYPE_HTML      TextFormatType = 3
)

// Enum value maps for TextFormatType.
var (
	TextFormatType_name = map[int32]string{
		0: "TEXT_FORMAT_TYPE_UNDEFINED",
		1: "TEXT_FORMAT_TYPE_PLAIN",
		2: "TEXT_FORMAT_TYPE_MARKDOWN",
		3: "TEXT_FORMAT_TYPE_HTML",
	}
	TextFormatType_value = map[string]int32{
		"TEXT_FORMAT_TYPE_UNDEFINED": 0,
		"TEXT_FORMAT_TYPE_PLAIN":     1,
		"TEXT_FORMAT_TYPE_MARKDOWN":  2,
		"TEXT_FORMAT_TYPE_HTML":      3,
	}
)

func (x TextFormatType) Enum() *TextFormatType {
	p := new(TextFormatType)
	*p = x
	return p
}

func (x TextFormatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextFormatType) Descriptor() protoreflect.EnumDescriptor {
	return file_chatwebhook_proto_enumTypes[3].Descriptor()
}

func (TextFormatType) Type() protoreflect.EnumType {
	return &file_chatwebhook_proto_enumTypes[3]
}

func (x TextFormatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextFormatType.Descriptor instead.
func (TextFormatType) EnumDescriptor() ([]byte, []int) {
	return file_chatwebhook_proto_rawDescGZIP(), []int{3}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformID    PlatformID             `protobuf:"varint,1,opt,name=platformID,proto3,enum=chatwebhook.PlatformID" json:"platformID,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_chatwebhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatwebhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_chatwebhook_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetPlatformID() PlatformID {
	if x != nil {
		return x.PlatformID
	}
	return PlatformID_platformIDUndefined
}

func (x *SubscribeRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NameReadable  *string                `protobuf:"bytes,4,opt,name=nameReadable,proto3,oneof" json:"nameReadable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_chatwebhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_chatwebhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_chatwebhook_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetNameReadable() string {
	if x != nil && x.NameReadable != nil {
		return *x.NameReadable
	}
	return ""
}

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      Currency               `protobuf:"varint,1,opt,name=currency,proto3,enum=chatwebhook.Currency" json:"currency,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_chatwebhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_chatwebhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_chatwebhook_proto_rawDescGZIP(), []int{2}
}

func (x *Money) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNDEFINED
}

func (x *Money) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	FormatType    TextFormatType         `protobuf:"varint,2,opt,name=formatType,proto3,enum=chatwebhook.TextFormatType" json:"formatType,omitempty"`
	InReplyTo     *string                `protobuf:"bytes,3,opt,name=inReplyTo,proto3,oneof" json:"inReplyTo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chatwebhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chatwebhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chatwebhook_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetFormatType() TextFormatType {
	if x != nil {
		return x.FormatType
	}
	return TextFormatType_TEXT_FORMAT_TYPE_UNDEFINED
}

func (x *Message) GetInReplyTo() string {
	if x != nil && x.InReplyTo != nil {
		return *x.InReplyTo
	}
	return ""
}

type Event struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAtUNIXNano uint64                 `protobuf:"varint,2,opt,name=createdAtUNIXNano,proto3" json:"createdAtUNIXNano,omitempty"`
	ExpiresAtUNIXNano *uint64                `protobuf:"varint,3,opt,name=expiresAtUNIXNano,proto3,oneof" json:"expiresAtUNIXNano,omitempty"`
	EventType         PlatformEventType      `protobuf:"varint,4,opt,name=eventType,proto3,enum=chatwebhook.PlatformEventType" json:"eventType,omitempty"`
	User              *User                  `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	TargetUser        *User                  `protobuf:"bytes,6,opt,name=targetUser,proto3,oneof" json:"targetUser,omitempty"`
	TargetChannel     *User                  `protobuf:"bytes,7,opt,name=targetChannel,proto3,oneof" json:"targetChannel,omitempty"`
	Message           *Message               `protobuf:"bytes,8,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Money             *Money                 `protobuf:"bytes,9,opt,name=money,proto3,oneof" json:"money,omitempty"`
	Tier              *string                `protobuf:"bytes,10,opt,name=tier,proto3,oneof" json:"tier,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_chatwebhook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_chatwebhook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_chatwebhook_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetCreatedAtUNIXNano() uint64 {
	if x != nil {
		return x.CreatedAtUNIXNano
	}
	return 0
}

func (x *Event) GetExpiresAtUNIXNano() uint64 {
	if x != nil && x.ExpiresAtUNIXNano != nil {
		return *x.ExpiresAtUNIXNano
	}
	return 0
}

func (x *Event) GetEventType() PlatformEventType {
	if x != nil {
		return x.EventType
	}
	return PlatformEventType_platformEventTypeUndefined
}

func (x *Event) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Event) GetTargetUser() *User {
	if x != nil {
		return x.TargetUser
	}
	return nil
}

func (x *Event) GetTargetChannel() *User {
	if x != nil {
		return x.TargetChannel
	}
	return nil
}

func (x *Event) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Event) GetMoney() *Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *Event) GetTier() string {
	if x != nil && x.Tier != nil {
		return *x.Tier
	}
	return ""
}

var File_chatwebhook_proto protoreflect.FileDescriptor

const file_chatwebhook_proto_rawDesc = "" +
	"\n" +
	"\x11chatwebhook.proto\x12\vchatwebhook\"c\n" +
	"\x10SubscribeRequest\x127\n" +
	"\n" +
	"platformID\x18\x01 \x01(\x0e2\x17.chatwebhook.PlatformIDR\n" +
	"platformID\x12\x16\n" +
	"\x06apiKey\x18\x02 \x01(\tR\x06apiKey\"x\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12'\n" +
	"\fnameReadable\x18\x04 \x01(\tH\x00R\fnameReadable\x88\x01\x01B\x0f\n" +
	"\r_nameReadable\"R\n" +
	"\x05Money\x121\n" +
	"\bcurrency\x18\x01 \x01(\x0e2\x15.chatwebhook.CurrencyR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"\x91\x01\n" +
	"\aMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12;\n" +
	"\n" +
	"formatType\x18\x02 \x01(\x0e2\x1b.chatwebhook.TextFormatTypeR\n" +
	"formatType\x12!\n" +
	"\tinReplyTo\x18\x03 \x01(\tH\x00R\tinReplyTo\x88\x01\x01B\f\n" +
	"\n" +
	"_inReplyTo\"\xa6\x04\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x11createdAtUNIXNano\x18\x02 \x01(\x04R\x11createdAtUNIXNano\x121\n" +
	"\x11expiresAtUNIXNano\x18\x03 \x01(\x04H\x00R\x11expiresAtUNIXNano\x88\x01\x01\x12<\n" +
	"\teventType\x18\x04 \x01(\x0e2\x1e.chatwebhook.PlatformEventTypeR\teventType\x12%\n" +
	"\x04user\x18\x05 \x01(\v2\x11.chatwebhook.UserR\x04user\x126\n" +
	"\n" +
	"targetUser\x18\x06 \x01(\v2\x11.chatwebhook.UserH\x01R\n" +
	"targetUser\x88\x01\x01\x12<\n" +
	"\rtargetChannel\x18\a \x01(\v2\x11.chatwebhook.UserH\x02R\rtargetChannel\x88\x01\x01\x123\n" +
	"\amessage\x18\b \x01(\v2\x14.chatwebhook.MessageH\x03R\amessage\x88\x01\x01\x12-\n" +
	"\x05money\x18\t \x01(\v2\x12.chatwebhook.MoneyH\x04R\x05money\x88\x01\x01\x12\x17\n" +
	"\x04tier\x18\n" +
	" \x01(\tH\x05R\x04tier\x88\x01\x01B\x14\n" +
	"\x12_expiresAtUNIXNanoB\r\n" +
	"\v_targetUserB\x10\n" +
	"\x0e_targetChannelB\n" +
	"\n" +
	"\b_messageB\b\n" +
	"\x06_moneyB\a\n" +
	"\x05_tier*f\n" +
	"\n" +
	"PlatformID\x12\x17\n" +
	"\x13platformIDUndefined\x10\x00\x12\x12\n" +
	"\x0eplatformIDKick\x10\x01\x12\x14\n" +
	"\x10platformIDTwitch\x10\x02\x12\x15\n" +
	"\x11platformIDYouTube\x10\x03*\xed\x04\n" +
	"\x11PlatformEventType\x12\x1e\n" +
	"\x1aplatformEventTypeUndefined\x10\x00\x12 \n" +
	"\x1cplatformEventTypeChatMessage\x10\x01\x12\x1a\n" +
	"\x16platformEventTypeCheer\x10\x02\x12\x1c\n" +
	"\x18platformEventTypeAdBreak\x10\x04\x12\x1b\n" +
	"\x17platformEventTypeFollow\x10\x06\x12\"\n" +
	"\x1dplatformEventTypeStreamOnline\x10\x80\x02\x12#\n" +
	"\x1eplatformEventTypeStreamOffline\x10\x81\x02\x12&\n" +
	"!platformEventTypeStreamInfoUpdate\x10\x82\x02\x12%\n" +
	" platformEventTypeSubscriptionNew\x10\x80\x04\x12)\n" +
	"$platformEventTypeSubscriptionRenewed\x10\x81\x04\x12(\n" +
	"#platformEventTypeGiftedSubscription\x10\x82\x04\x12\x1a\n" +
	"\x15platformEventTypeRaid\x10\x80\x06\x12,\n" +
	"'platformEventTypeChannelShoutoutReceive\x10\x81\x06\x12\x19\n" +
	"\x14platformEventTypeBan\x10\x80\b\x12!\n" +
	"\x1cplatformEventTypeAutoModHold\x10\x81\b\x12,\n" +
	"'platformEventTypeChannelPointRedemption\x10\x80\n" +
	"\x12\x1c\n" +
	"\x16platformEventTypeOther\x10\xff\xff\x03*\x9b\x01\n" +
	"\bCurrency\x12\x16\n" +
	"\x12CURRENCY_UNDEFINED\x10\x00\x12\x10\n" +
	"\fCURRENCY_USD\x10\x01\x12\x10\n" +
	"\fCURRENCY_EUR\x10\x02\x12\x10\n" +
	"\fCURRENCY_GBP\x10\x03\x12\x10\n" +
	"\fCURRENCY_JPY\x10\x04\x12\x19\n" +
	"\x14CURRENCY_TWITCH_BITS\x10\x80\b\x12\x14\n" +
	"\x0eCURRENCY_OTHER\x10\xff\xff\x03*\x86\x01\n" +
	"\x0eTextFormatType\x12\x1e\n" +
	"\x1aTEXT_FORMAT_TYPE_UNDEFINED\x10\x00\x12\x1a\n" +
	"\x16TEXT_FORMAT_TYPE_PLAIN\x10\x01\x12\x1d\n" +
	"\x19TEXT_FORMAT_TYPE_MARKDOWN\x10\x02\x12\x19\n" +
	"\x15TEXT_FORMAT_TYPE_HTML\x10\x032Q\n" +
	"\vChatWebHook\x12B\n" +
	"\tSubscribe\x12\x1d.chatwebhook.SubscribeRequest\x1a\x12.chatwebhook.Event\"\x000\x01BJZHgithub.com/xaionaro-go/chatwebhook/pkg/grpc/protobuf/go/chatwebhook_grpcb\x06proto3"

var (
	file_chatwebhook_proto_rawDescOnce sync.Once
	file_chatwebhook_proto_rawDescData []byte
)

func file_chatwebhook_proto_rawDescGZIP() []byte {
	file_chatwebhook_proto_rawDescOnce.Do(func() {
		file_chatwebhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatwebhook_proto_rawDesc), len(file_chatwebhook_proto_rawDesc)))
	})
	return file_chatwebhook_proto_rawDescData
}

var file_chatwebhook_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_chatwebhook_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chatwebhook_proto_goTypes = []any{
	(PlatformID)(0),          // 0: chatwebhook.PlatformID
	(PlatformEventType)(0),   // 1: chatwebhook.PlatformEventType
	(Currency)(0),            // 2: chatwebhook.Currency
	(TextFormatType)(0),      // 3: chatwebhook.TextFormatType
	(*SubscribeRequest)(nil), // 4: chatwebhook.SubscribeRequest
	(*User)(nil),             // 5: chatwebhook.User
	(*Money)(nil),            // 6: chatwebhook.Money
	(*Message)(nil),          // 7: chatwebhook.Message
	(*Event)(nil),            // 8: chatwebhook.Event
}
var file_chatwebhook_proto_depIdxs = []int32{
	0,  // 0: chatwebhook.SubscribeRequest.platformID:type_name -> chatwebhook.PlatformID
	2,  // 1: chatwebhook.Money.currency:type_name -> chatwebhook.Currency
	3,  // 2: chatwebhook.Message.formatType:type_name -> chatwebhook.TextFormatType
	1,  // 3: chatwebhook.Event.eventType:type_name -> chatwebhook.PlatformEventType
	5,  // 4: chatwebhook.Event.user:type_name -> chatwebhook.User
	5,  // 5: chatwebhook.Event.targetUser:type_name -> chatwebhook.User
	5,  // 6: chatwebhook.Event.targetChannel:type_name -> chatwebhook.User
	7,  // 7: chatwebhook.Event.message:type_name -> chatwebhook.Message
	6,  // 8: chatwebhook.Event.money:type_name -> chatwebhook.Money
	4,  // 9: chatwebhook.ChatWebHook.Subscribe:input_type -> chatwebhook.SubscribeRequest
	8,  // 10: chatwebhook.ChatWebHook.Subscribe:output_type -> chatwebhook.Event
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_chatwebhook_proto_init() }
func file_chatwebhook_proto_init() {
	if File_chatwebhook_proto != nil {
		return
	}
	file_chatwebhook_proto_msgTypes[1].OneofWrappers = []any{}
	file_chatwebhook_proto_msgTypes[3].OneofWrappers = []any{}
	file_chatwebhook_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatwebhook_proto_rawDesc), len(file_chatwebhook_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatwebhook_proto_goTypes,
		DependencyIndexes: file_chatwebhook_proto_depIdxs,
		EnumInfos:         file_chatwebhook_proto_enumTypes,
		MessageInfos:      file_chatwebhook_proto_msgTypes,
	}.Build()
	File_chatwebhook_proto = out.File
	file_chatwebhook_proto_goTypes = nil
	file_chatwebhook_proto_depIdxs = nil
}
